#' Precomputed mixgb imputed datasets for `newborn`
#'
#' A small precomputed list object containing `m` imputed datasets generated by
#' `mixgb::mixgb()` on the `newborn` example data. This dataset is included so
#' that users can run plotting examples without installing `mixgb`.
#' @docType  data
#' @usage data(imp_newborn)
#' @format A list of `m` data.frames (each a completed dataset) created by
#'   `mixgb::mixgb()` in development.
#' @source Generated during package development with `mixgb::mixgb()`.
"imp_newborn"
