#' Precomputed mixgb imputed datasets for `nhanes3_newborn`
#'
#' A small precomputed list object containing `m` imputed datasets generated by
#' `mixgb::mixgb()` on the `nhanes3_newborn` example data. This dataset is included so
#' that users can run plotting examples without installing `mixgb`.
#' @docType  data
#' @usage data(imp_nhanes3_newborn)
#' @format A list of `m` data.frames (each a completed dataset) created by
#'   `mixgb::mixgb()` in development.
#' @source Generated during package development with `mixgb::mixgb()`.
#' @examples
#' data(imp_nhanes3_newborn)
#' str(imp_nhanes3_newborn)
"imp_nhanes3_newborn"
