#' Overlay density plots for multiply imputed values for a single numeric variable
#' @description Plot overlay density curves of observed values versus m sets of imputed values for a specified numeric variable using \pkg{ggplot2}.
#' @param imputation.list A list of \code{m} imputed datasets returned by the \code{mixgb} imputer, or other package.
#' @param var.name The name of a numeric variable of interest.
#' @param original.data The original data with missing values.
#' @param true.data The true data without missing values. This is generally unknown in practice. If the true data is known (e.g., in cases where it is generated by simulation), it can be specified in this argument. The output will then have an extra panel called \code{MaskedTrue}, which shows values originally observed but intentionally made missing.
#' @param color.pal A vector of hex color codes for the observed and m sets of imputed values panels. The vector should be of length \code{m+1}. Default: NULL (use "gray40" for the observed panel, use ggplot2 default colors for other panels.)
#' @importFrom scales hue_pal
#' @importFrom tidyr pivot_longer
#' @importFrom rlang .data
#' @importFrom grDevices nclass.Sturges
#' @importFrom stats density
#' @importFrom ggplot2 ggplot aes vars geom_histogram geom_density facet_grid labs scale_color_manual scale_fill_manual guides theme element_text after_stat
#' @return Histogram with density plots
#' @export
#' @examples
#' # obtain m multiply datasets
#' params <- list(max_depth = 3, subsample = 0.8, nthread = 2)
#' imputed.data <- mixgb(data = nhanes3, m = 3, xgb.params = params, nrounds = 30)
#'
#' # plot the multiply imputed values for variable "BMPHEAD"
#' plot_hist(
#'   imputation.list = imputed.data, var.name = "BMPHEAD",
#'   original.data = nhanes3
#' )
plot_density_facet <- function(imputation.lists, methods, var.name, original.data, true.data = NULL, color.pal = NULL) {

  n.methods<-length(methods)
  imp.sum.list<-vector(mode="list", length=n.methods)

  for(i in 1:n.methods){
    Types <- feature_type(imputation.lists[[i]][[1]])
    if (Types[var.name] == "binary" | Types[var.name] == "multiclass") {
      stop(paste("The variable", var.name, " is a factor. Please use plot_bar() instead."))
    }

     output<- summary1var(imputation.list = imputation.lists[[i]], var.name = var.name, original.data = original.data, true.data = true.data, color.pal = color.pal)
     imp.sum.list[[i]]<-output$all.dt
  }

  color.pal <- output$color.pal
  all.dt<-rbindlist(imp.sum.list)
  all.dt[,"methods"]<-factor(rep(methods,each=nrow(imp.sum.list[[1]])),levels = methods)



  ggplot(data = all.dt, aes(x = .data[[var.name]])) +
    # geom_histogram(alpha = 0.5, aes(fill = m.set, color = m.set, y = ..density..), breaks = breaks) +
    #geom_histogram(alpha = 0.5, aes(fill = m.set, color = m.set, y = after_stat(density)), breaks = breaks) +
    geom_density(linewidth = 0.5, alpha = 0.3, aes(color = m.set)) +
    facet_grid(cols = vars(methods)) +
    labs(title = "Density curve", subtitle = paste(" imputed sets for variable: ", var.name)) +
    scale_color_manual(values = color.pal) +
    guides(color = guide_legend(title="Imputed set"))+
    #scale_fill_manual(values = color.pal) +
    #guides(color = "none", fill = "none", linetype = "none") +
    theme(
      strip.text = element_text(face = "bold"),
      plot.title = element_text(face = "bold"),
      plot.subtitle = element_text(face = "bold")
    )
}
